### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by ricardo123321**
this is  a clone of the new york times page in witch

The header is positioned fixed to keep it on the top of the page
The article is using divs for spacing between paragraphs
Aside is positioned absolutely to keep it on the right side of the page.
Aside is also using media queries rules in order not to make it overlap article content on changing the width of the screen
The suggested articles section is using grid and media queries with display: none to change the size of itself
There are uploaded fonts with similar names, but with different attributes to be used in page
Icons are implemented with use of fontawesome.com

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your project looks :+1: amazing!
Here are the things to fix before this project can be approved:
  
* [ ] The NY Times logo should be a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))
* [ ] Footer should have a fixed position (it sticks to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)
image
* [ ] It's better to add more width to navbar to look more like original:
image


Original:
image

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴

Hi **Team** your project looks great  👍 congratulations we are almost there. Let us address the comment made by the previous reviewer before we proceed. 🙂 
- The ```New York Times``` logo is a link. We can solve this by wrapping ```<a>``` around the `````` on ```line 20```

Kindly make this change and submit code review 👨‍💻 
_Happy coding_
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo-9738b0128/)

**Comment by uryelah** [comment]
Hello **Ricardo Vera Trallero** & **Arslan Bisharat Arslan**, I'm Sarah, your reviewer for this PR 👩‍🚀 

First of all, you did an amazing job with this project, it looks like a quasi perfect clone! 🎊 🚀 

**Great job at:** 🥇
- making a very professional readme file and PR message
- good use of the :hover effect
- positioning the navbar and it's elements really well
- good attention to colors and font styles
- great job at the theory of inflation area, that's a hard one to nail

**You still need to work on a couple of details before you can move on to the next project though**
-----

### Required changes 🛠 
### 

The fixed footer.note at the bottom of the page has it's text vertically aligned in the original.
- [ ] Please align the text vertically in your clone
Your version:
Screenshot_2020-03-04 Space Ripples Reveal Big Bang’s Smoking Gun

Original:
Screenshot_2020-03-04 Space Ripples Reveal Big Bang’s Smoking Gun(2)


- [ ] The logo image at the footer is stretched vertically. Make sure it's not distorted anymore.
Screenshot_2020-03-04 Space Ripples Reveal Big Bang’s Smoking Gun(1)

- [ ] Please don't use ids for styling in your CSS file. [Reasons why here.](https://dev.to/clairecodes/reasons-not-to-use-ids-in-css-4ni4)
-------
###Optional Changes
 
- [ ] There's a bug with your bold markup at the readme file. Fix it to make your repo more profesional.
Screenshot_2020-03-04 arslanbisharat New-York-Times-Page

------

**Please fix the required changes 👷  before asking for a new code review**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by uryelah** [comment]
Good job fixing the required changes guys!

### Your project is approved! 🎊 🥅 💛 
### 
**You may close this Pull Request and merge the changes**

-------

**Keep being awesome devs and good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
